{
 "title": "Nginx Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Waiting Connection vs Container Start Actions",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(engine_daemon_container_actions_seconds_sum{action=\"create\"}[1m])*100000",
     "legendFormat": "container start"
    },
    {
     "expr": "rate(nginx_connections_active[5m])",
     "legendFormat": "nginx connections active"
    },
    {
     "expr": "rate(nginx_connections_waiting[5m])",
     "legendFormat": "nginx connections waiting"
    }
   ]
  },
  {
   "title": "Nginx Connections /5M",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_connections_writing[5m])",
     "legendFormat": "writing"
    },
    {
     "expr": "rate(nginx_connections_waiting[5m])",
     "legendFormat": "waiting"
    },
    {
     "expr": "rate(nginx_connections_handled[5m])",
     "legendFormat": "handled"
    },
    {
     "expr": "rate(nginx_connections_reading[5m])",
     "legendFormat": "reading"
    },
    {
     "expr": "rate(nginx_connections_accepted[5m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(nginx_connections_active[5m])",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Nginx UP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginx_up" }
   ]
  }
 ]
}