{
 "title": "Sysadmin Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Connections Accepted/1m + Connections Active/1m",
   "type": "graph",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_connections_accepted[1m])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "rate(nginx_connections_active[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Connections Accepted/5m + Connections Active/5m",
   "type": "graph",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_connections_accepted[5m])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "rate(nginx_connections_active[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(engine_daemon_container_actions_seconds_sum[1m])",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Nginx UP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginx_up" }
   ]
  },
  {
   "title": "Memory Usage of Host",
   "type": "graph",
   "description": "This show better data once you expose docker metrics: https://blog.sebas.tech/blog/docker-prometheus-ufw\n\nYou also need to open port 9323",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"docker_host\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "engine_daemon_engine_memory_bytes{job=\"docker_host\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}